from .base import Worker as Worker
from _typeshed import Incomplete

logger: Incomplete

class Supervisor(Worker):
    def __init__(self, *args, **kwargs) -> None: ...
    def __getattr__(self, item): ...
    def __getitem__(self, item): ...
    async def init(self): ...
    def __call__(self, *args, **kwargs): ...
    def get_child_config(self, *args, **kwargs): ...
    def create_child(self, *args, **kwargs): ...
    async def get(self): ...
    async def put(self, *args, **kwargs): ...
    async def work(self): ...
    async def stop(self, force: bool = ...): ...
    async def status(self): ...
