# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sportmonks import schemas  # noqa: F401


class SportOddsPreMatchByFixtureAndMarketIdResponseData(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['SportOddsPreMatchByFixtureAndMarketIdResponseDataItem']:
            return SportOddsPreMatchByFixtureAndMarketIdResponseDataItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['SportOddsPreMatchByFixtureAndMarketIdResponseDataItem'], typing.List['SportOddsPreMatchByFixtureAndMarketIdResponseDataItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'SportOddsPreMatchByFixtureAndMarketIdResponseData':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'SportOddsPreMatchByFixtureAndMarketIdResponseDataItem':
        return super().__getitem__(i)

from sportmonks.model.sport_odds_pre_match_by_fixture_and_market_id_response_data_item import SportOddsPreMatchByFixtureAndMarketIdResponseDataItem
