# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.my_leagues_response_subscription_item_add_ons import MyLeaguesResponseSubscriptionItemAddOns
from sportmonks.type.my_leagues_response_subscription_item_meta import MyLeaguesResponseSubscriptionItemMeta
from sportmonks.type.my_leagues_response_subscription_item_plans import MyLeaguesResponseSubscriptionItemPlans
from sportmonks.type.my_leagues_response_subscription_item_widgets import MyLeaguesResponseSubscriptionItemWidgets

class RequiredMyLeaguesResponseSubscriptionItem(TypedDict):
    pass

class OptionalMyLeaguesResponseSubscriptionItem(TypedDict, total=False):
    meta: MyLeaguesResponseSubscriptionItemMeta

    plans: MyLeaguesResponseSubscriptionItemPlans

    add_ons: MyLeaguesResponseSubscriptionItemAddOns

    widgets: MyLeaguesResponseSubscriptionItemWidgets

class MyLeaguesResponseSubscriptionItem(RequiredMyLeaguesResponseSubscriptionItem, OptionalMyLeaguesResponseSubscriptionItem):
    pass
