# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.my_resources_response_subscription_item_add_ons import MyResourcesResponseSubscriptionItemAddOns
from sportmonks.type.my_resources_response_subscription_item_meta import MyResourcesResponseSubscriptionItemMeta
from sportmonks.type.my_resources_response_subscription_item_plans import MyResourcesResponseSubscriptionItemPlans
from sportmonks.type.my_resources_response_subscription_item_widgets import MyResourcesResponseSubscriptionItemWidgets

class RequiredMyResourcesResponseSubscriptionItem(TypedDict):
    pass

class OptionalMyResourcesResponseSubscriptionItem(TypedDict, total=False):
    meta: MyResourcesResponseSubscriptionItemMeta

    plans: MyResourcesResponseSubscriptionItemPlans

    add_ons: MyResourcesResponseSubscriptionItemAddOns

    widgets: MyResourcesResponseSubscriptionItemWidgets

class MyResourcesResponseSubscriptionItem(RequiredMyResourcesResponseSubscriptionItem, OptionalMyResourcesResponseSubscriptionItem):
    pass
