# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.odds_bookmakers_search_response_subscription_item_add_ons import OddsBookmakersSearchResponseSubscriptionItemAddOns
from sportmonks.type.odds_bookmakers_search_response_subscription_item_meta import OddsBookmakersSearchResponseSubscriptionItemMeta
from sportmonks.type.odds_bookmakers_search_response_subscription_item_plans import OddsBookmakersSearchResponseSubscriptionItemPlans
from sportmonks.type.odds_bookmakers_search_response_subscription_item_widgets import OddsBookmakersSearchResponseSubscriptionItemWidgets

class RequiredOddsBookmakersSearchResponseSubscriptionItem(TypedDict):
    pass

class OptionalOddsBookmakersSearchResponseSubscriptionItem(TypedDict, total=False):
    meta: OddsBookmakersSearchResponseSubscriptionItemMeta

    plans: OddsBookmakersSearchResponseSubscriptionItemPlans

    add_ons: OddsBookmakersSearchResponseSubscriptionItemAddOns

    widgets: OddsBookmakersSearchResponseSubscriptionItemWidgets

class OddsBookmakersSearchResponseSubscriptionItem(RequiredOddsBookmakersSearchResponseSubscriptionItem, OptionalOddsBookmakersSearchResponseSubscriptionItem):
    pass
