# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_venue_by_id_response_data import SportVenueByIdResponseData
from sportmonks.type.sport_venue_by_id_response_rate_limit import SportVenueByIdResponseRateLimit
from sportmonks.type.sport_venue_by_id_response_subscription import SportVenueByIdResponseSubscription

class RequiredSportVenueByIdResponse(TypedDict):
    pass

class OptionalSportVenueByIdResponse(TypedDict, total=False):
    data: SportVenueByIdResponseData

    subscription: SportVenueByIdResponseSubscription

    rate_limit: SportVenueByIdResponseRateLimit

    timezone: str

class SportVenueByIdResponse(RequiredSportVenueByIdResponse, OptionalSportVenueByIdResponse):
    pass
