# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_standings_by_round_id_response_data import SportStandingsByRoundIdResponseData
from sportmonks.type.sport_standings_by_round_id_response_rate_limit import SportStandingsByRoundIdResponseRateLimit
from sportmonks.type.sport_standings_by_round_id_response_subscription import SportStandingsByRoundIdResponseSubscription

class RequiredSportStandingsByRoundIdResponse(TypedDict):
    pass

class OptionalSportStandingsByRoundIdResponse(TypedDict, total=False):
    data: SportStandingsByRoundIdResponseData

    message: str

    subscription: SportStandingsByRoundIdResponseSubscription

    rate_limit: SportStandingsByRoundIdResponseRateLimit

    timezone: str

class SportStandingsByRoundIdResponse(RequiredSportStandingsByRoundIdResponse, OptionalSportStandingsByRoundIdResponse):
    pass
