# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_teams_by_id_response_data import SportTeamsByIdResponseData
from sportmonks.type.sport_teams_by_id_response_rate_limit import SportTeamsByIdResponseRateLimit
from sportmonks.type.sport_teams_by_id_response_subscription import SportTeamsByIdResponseSubscription

class RequiredSportTeamsByIdResponse(TypedDict):
    pass

class OptionalSportTeamsByIdResponse(TypedDict, total=False):
    data: SportTeamsByIdResponseData

    subscription: SportTeamsByIdResponseSubscription

    rate_limit: SportTeamsByIdResponseRateLimit

    timezone: str

class SportTeamsByIdResponse(RequiredSportTeamsByIdResponse, OptionalSportTeamsByIdResponse):
    pass
