# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_news_upcoming_pre_match_response_subscription_item_add_ons import SportNewsUpcomingPreMatchResponseSubscriptionItemAddOns
from sportmonks.type.sport_news_upcoming_pre_match_response_subscription_item_meta import SportNewsUpcomingPreMatchResponseSubscriptionItemMeta
from sportmonks.type.sport_news_upcoming_pre_match_response_subscription_item_plans import SportNewsUpcomingPreMatchResponseSubscriptionItemPlans

class RequiredSportNewsUpcomingPreMatchResponseSubscriptionItem(TypedDict):
    pass

class OptionalSportNewsUpcomingPreMatchResponseSubscriptionItem(TypedDict, total=False):
    meta: SportNewsUpcomingPreMatchResponseSubscriptionItemMeta

    plans: SportNewsUpcomingPreMatchResponseSubscriptionItemPlans

    add_ons: SportNewsUpcomingPreMatchResponseSubscriptionItemAddOns

class SportNewsUpcomingPreMatchResponseSubscriptionItem(RequiredSportNewsUpcomingPreMatchResponseSubscriptionItem, OptionalSportNewsUpcomingPreMatchResponseSubscriptionItem):
    pass
