# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_coaches_latest_response_subscription_item_add_ons import SportCoachesLatestResponseSubscriptionItemAddOns
from sportmonks.type.sport_coaches_latest_response_subscription_item_meta import SportCoachesLatestResponseSubscriptionItemMeta
from sportmonks.type.sport_coaches_latest_response_subscription_item_plans import SportCoachesLatestResponseSubscriptionItemPlans
from sportmonks.type.sport_coaches_latest_response_subscription_item_widgets import SportCoachesLatestResponseSubscriptionItemWidgets

class RequiredSportCoachesLatestResponseSubscriptionItem(TypedDict):
    pass

class OptionalSportCoachesLatestResponseSubscriptionItem(TypedDict, total=False):
    meta: SportCoachesLatestResponseSubscriptionItemMeta

    plans: SportCoachesLatestResponseSubscriptionItemPlans

    add_ons: SportCoachesLatestResponseSubscriptionItemAddOns

    widgets: SportCoachesLatestResponseSubscriptionItemWidgets

class SportCoachesLatestResponseSubscriptionItem(RequiredSportCoachesLatestResponseSubscriptionItem, OptionalSportCoachesLatestResponseSubscriptionItem):
    pass
