# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_commentaries_by_fixture_id_response_subscription_item_add_ons import SportCommentariesByFixtureIdResponseSubscriptionItemAddOns
from sportmonks.type.sport_commentaries_by_fixture_id_response_subscription_item_meta import SportCommentariesByFixtureIdResponseSubscriptionItemMeta
from sportmonks.type.sport_commentaries_by_fixture_id_response_subscription_item_plans import SportCommentariesByFixtureIdResponseSubscriptionItemPlans
from sportmonks.type.sport_commentaries_by_fixture_id_response_subscription_item_widgets import SportCommentariesByFixtureIdResponseSubscriptionItemWidgets

class RequiredSportCommentariesByFixtureIdResponseSubscriptionItem(TypedDict):
    pass

class OptionalSportCommentariesByFixtureIdResponseSubscriptionItem(TypedDict, total=False):
    meta: SportCommentariesByFixtureIdResponseSubscriptionItemMeta

    plans: SportCommentariesByFixtureIdResponseSubscriptionItemPlans

    add_ons: SportCommentariesByFixtureIdResponseSubscriptionItemAddOns

    widgets: SportCommentariesByFixtureIdResponseSubscriptionItemWidgets

class SportCommentariesByFixtureIdResponseSubscriptionItem(RequiredSportCommentariesByFixtureIdResponseSubscriptionItem, OptionalSportCommentariesByFixtureIdResponseSubscriptionItem):
    pass
