# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal


class RequiredSportSquadsByTeamIdResponseDataItem(TypedDict):
    pass

class OptionalSportSquadsByTeamIdResponseDataItem(TypedDict, total=False):
    id: typing.Union[int, float]

    transfer_id: typing.Optional[typing.Union[int, float]]

    player_id: typing.Union[int, float]

    team_id: typing.Union[int, float]

    position_id: typing.Union[int, float]

    detailed_position_id: typing.Union[int, float]

    active: bool

    yersey_number: typing.Optional[typing.Union[int, float]]

    start: str

    end: str

class SportSquadsByTeamIdResponseDataItem(RequiredSportSquadsByTeamIdResponseDataItem, OptionalSportSquadsByTeamIdResponseDataItem):
    pass
