# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_commentaries_by_fixture_id_response_data import SportCommentariesByFixtureIdResponseData
from sportmonks.type.sport_commentaries_by_fixture_id_response_rate_limit import SportCommentariesByFixtureIdResponseRateLimit
from sportmonks.type.sport_commentaries_by_fixture_id_response_subscription import SportCommentariesByFixtureIdResponseSubscription

class RequiredSportCommentariesByFixtureIdResponse(TypedDict):
    pass

class OptionalSportCommentariesByFixtureIdResponse(TypedDict, total=False):
    data: SportCommentariesByFixtureIdResponseData

    message: str

    subscription: SportCommentariesByFixtureIdResponseSubscription

    rate_limit: SportCommentariesByFixtureIdResponseRateLimit

    timezone: str

class SportCommentariesByFixtureIdResponse(RequiredSportCommentariesByFixtureIdResponse, OptionalSportCommentariesByFixtureIdResponse):
    pass
