# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_rivals_all_response_subscription_item_add_ons import SportRivalsAllResponseSubscriptionItemAddOns
from sportmonks.type.sport_rivals_all_response_subscription_item_meta import SportRivalsAllResponseSubscriptionItemMeta
from sportmonks.type.sport_rivals_all_response_subscription_item_plans import SportRivalsAllResponseSubscriptionItemPlans

class RequiredSportRivalsAllResponseSubscriptionItem(TypedDict):
    pass

class OptionalSportRivalsAllResponseSubscriptionItem(TypedDict, total=False):
    meta: SportRivalsAllResponseSubscriptionItemMeta

    plans: SportRivalsAllResponseSubscriptionItemPlans

    add_ons: SportRivalsAllResponseSubscriptionItemAddOns

class SportRivalsAllResponseSubscriptionItem(RequiredSportRivalsAllResponseSubscriptionItem, OptionalSportRivalsAllResponseSubscriptionItem):
    pass
