from _typeshed import Incomplete
from aioworkers.worker.subprocess import Subprocess as Subprocess

class BaseUpdater(Subprocess):
    def set_config(self, config) -> None: ...
    async def can_restart(self): ...
    async def wait_restart(self) -> None: ...
    async def restart(self) -> None: ...
    async def can_update(self): ...
    async def update(self) -> None: ...
    async def run(self, value: Incomplete | None = ...) -> None: ...

class PipUpdater(BaseUpdater):
    pip: Incomplete
    current_version: Incomplete
    new_version: Incomplete
    def set_config(self, config) -> None: ...
    async def can_update(self): ...
    @classmethod
    def version(cls, package): ...
    async def update(self) -> None: ...
