export default function langExtToReadable(ext: string) {
    return langExtToReadableMap[ext];
}

const langExtToReadableMap: { [key: string]: string } = {
    bat: 'Batch',
    coffee: 'Coffee',
    erl: 'Erlang',
    hs: 'Haskell',
    lua: 'Lua',
    md: 'Markdown',
    matlab: 'MATLAB',
    m: 'Objective-C',
    c: 'C',
    cpp: 'C++',
    cc: 'C++ Source',
    h: 'C++ Header',
    hh: 'C++ H-Header',
    cs: 'C#',
    css: 'CSS',
    go: 'Go',
    html: 'HTML',
    htm: 'HTM',
    java: 'Java',
    js: 'JavaScript',
    ts: 'TypeScript',
    dart: 'Dart',
    scala: 'Scala',
    sql: 'SQL',
    pl: 'Perl',
    php: 'PHP',
    py: 'Python',
    pyc: 'Python-C',
    ps1: 'PowerShell',
    r: 'R',
    sh: 'Bash',
    swift: 'Swift',
    rb: 'Ruby',
    tex: 'TeX',
    text: 'PlainTextGrammar',
    txt: 'PlainTextGrammar',
    rs: 'Rust',
    json: 'JSON',
    yml: 'YAML',
    yaml: 'YAML',
    toml: 'TOML',
    xml: 'XML',
    groovy: 'Groovy',
    kt: 'Kotlin',
    clj: 'Clojure',
    el: 'Lisp',
    ex: 'Elixir',
};
