# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kr8_protobuf import analyzer_pb2 as kr8__protobuf_dot_analyzer__pb2
from kr8_protobuf import common_pb2 as kr8__protobuf_dot_common__pb2


class AnalyzerControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPosts = channel.unary_unary(
                '/analyzer.AnalyzerController/GetPosts',
                request_serializer=kr8__protobuf_dot_common__pb2.GetItemByID.SerializeToString,
                response_deserializer=kr8__protobuf_dot_analyzer__pb2.Posts.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/analyzer.AnalyzerController/GetPost',
                request_serializer=kr8__protobuf_dot_common__pb2.GetItemByID.SerializeToString,
                response_deserializer=kr8__protobuf_dot_analyzer__pb2.Post.FromString,
                )


class AnalyzerControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyzerControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosts,
                    request_deserializer=kr8__protobuf_dot_common__pb2.GetItemByID.FromString,
                    response_serializer=kr8__protobuf_dot_analyzer__pb2.Posts.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=kr8__protobuf_dot_common__pb2.GetItemByID.FromString,
                    response_serializer=kr8__protobuf_dot_analyzer__pb2.Post.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analyzer.AnalyzerController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalyzerController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analyzer.AnalyzerController/GetPosts',
            kr8__protobuf_dot_common__pb2.GetItemByID.SerializeToString,
            kr8__protobuf_dot_analyzer__pb2.Posts.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analyzer.AnalyzerController/GetPost',
            kr8__protobuf_dot_common__pb2.GetItemByID.SerializeToString,
            kr8__protobuf_dot_analyzer__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
