
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-19T09:28:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfb795c3484f893c05693dca6c4566d630abca82",
 "version": "2023.7.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
