VERSION_YEAR = 2023
VERSION_MONTH = int('07')
VERSION_DAY = int('20')
VERSION_HOUR = int('03')
VERSION_MINUTE = int('44')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202307200344
version_date = '2023/07/20 03:44'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
