# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class OrmRunEdges(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'created_by': 'OrmUser',
        'project': 'OrmProject',
        'run_execs': 'list[OrmRunExecution]',
        'run_specs': 'list[OrmRunSpec]'
    }

    attribute_map = {
        'created_by': 'created_by',
        'project': 'project',
        'run_execs': 'run_execs',
        'run_specs': 'run_specs'
    }

    def __init__(self, created_by=None, project=None, run_execs=None, run_specs=None, local_vars_configuration=None):  # noqa: E501
        """OrmRunEdges - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._created_by = None
        self._project = None
        self._run_execs = None
        self._run_specs = None
        self.discriminator = None

        if created_by is not None:
            self.created_by = created_by
        if project is not None:
            self.project = project
        if run_execs is not None:
            self.run_execs = run_execs
        if run_specs is not None:
            self.run_specs = run_specs

    @property
    def created_by(self):
        """Gets the created_by of this OrmRunEdges.  # noqa: E501


        :return: The created_by of this OrmRunEdges.  # noqa: E501
        :rtype: OrmUser
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this OrmRunEdges.


        :param created_by: The created_by of this OrmRunEdges.  # noqa: E501
        :type created_by: OrmUser
        """

        self._created_by = created_by

    @property
    def project(self):
        """Gets the project of this OrmRunEdges.  # noqa: E501


        :return: The project of this OrmRunEdges.  # noqa: E501
        :rtype: OrmProject
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this OrmRunEdges.


        :param project: The project of this OrmRunEdges.  # noqa: E501
        :type project: OrmProject
        """

        self._project = project

    @property
    def run_execs(self):
        """Gets the run_execs of this OrmRunEdges.  # noqa: E501


        :return: The run_execs of this OrmRunEdges.  # noqa: E501
        :rtype: list[OrmRunExecution]
        """
        return self._run_execs

    @run_execs.setter
    def run_execs(self, run_execs):
        """Sets the run_execs of this OrmRunEdges.


        :param run_execs: The run_execs of this OrmRunEdges.  # noqa: E501
        :type run_execs: list[OrmRunExecution]
        """

        self._run_execs = run_execs

    @property
    def run_specs(self):
        """Gets the run_specs of this OrmRunEdges.  # noqa: E501


        :return: The run_specs of this OrmRunEdges.  # noqa: E501
        :rtype: list[OrmRunSpec]
        """
        return self._run_specs

    @run_specs.setter
    def run_specs(self, run_specs):
        """Sets the run_specs of this OrmRunEdges.


        :param run_specs: The run_specs of this OrmRunEdges.  # noqa: E501
        :type run_specs: list[OrmRunSpec]
        """

        self._run_specs = run_specs

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrmRunEdges):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrmRunEdges):
            return True

        return self.to_dict() != other.to_dict()
