
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-17T15:16:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d77a378f3ac724af4481ec35b82557cb2ac6c6b",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
