
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-20T11:17:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4bd9f9e23114e2dc385b4e0968d4af08082bfea",
 "version": "0.2.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
