# constants
CURRENT_STATUS = 0
SKIN_RETROFIT = 1
SYSTEM_RETROFIT_AND_PV = 2
SKIN_RETROFIT_AND_SYSTEM_RETROFIT_AND_PV = 3
RETROFITTING_SCENARIOS = [
  CURRENT_STATUS,
  SKIN_RETROFIT,
  SYSTEM_RETROFIT_AND_PV,
  SKIN_RETROFIT_AND_SYSTEM_RETROFIT_AND_PV
]