
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-19T00:41:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d27fe86d162c92ca55cceafbe0678ee1f1f638c",
 "version": "4.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
