# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ...hacker.v1 import hacker_service_pb2 as hacker_dot_v1_dot_hacker__service__pb2


class HackerServiceStub(object):
    """The service that handles the CRUD of Hacker.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateHacker = channel.unary_unary(
                '/hacker.v1.HackerService/CreateHacker',
                request_serializer=hacker_dot_v1_dot_hacker__service__pb2.CreateHackerRequest.SerializeToString,
                response_deserializer=hacker_dot_v1_dot_hacker__service__pb2.CreateHackerResponse.FromString,
                )


class HackerServiceServicer(object):
    """The service that handles the CRUD of Hacker.
    """

    def CreateHacker(self, request, context):
        """Creates a Hacker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HackerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateHacker': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHacker,
                    request_deserializer=hacker_dot_v1_dot_hacker__service__pb2.CreateHackerRequest.FromString,
                    response_serializer=hacker_dot_v1_dot_hacker__service__pb2.CreateHackerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hacker.v1.HackerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HackerService(object):
    """The service that handles the CRUD of Hacker.
    """

    @staticmethod
    def CreateHacker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hacker.v1.HackerService/CreateHacker',
            hacker_dot_v1_dot_hacker__service__pb2.CreateHackerRequest.SerializeToString,
            hacker_dot_v1_dot_hacker__service__pb2.CreateHackerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
