from setuptools import setup


setup(
    name="trajectopy",
    version=open("trajectopy/version", "r").read(),
    description="Trajectory Evaluation in Python",
    author="Gereon Tombrink",
    author_email="tombrink@igg.uni-bonn.de",
    url="https://github.com/gereon-t/trajectopy",
    license="GPLv3",
    long_description=open("README.md", "r").read(),
    long_description_content_type="text/markdown",
    keywords=["trajectory", "evaluation", "alignment", "similarity", "leverarm", "epsg", "robotics"],
    packages=[
        "trajectopy",
        "trajectopy.alignment",
        "trajectopy.alignment.functional_model",
        "trajectopy.approximation",
        "trajectopy.evaluation",
        "trajectopy.gui",
        "trajectopy.gui.managers",
        "trajectopy.gui.models",
        "trajectopy.gui.requests",
        "trajectopy.gui.views",
        "trajectopy.plotting",
        "trajectopy.settings",
        "trajectopy.util",
    ],
    package_data={"trajectopy": ["version", "LICENSE", "gui/resources/*", "plotting/default.mplstyle"]},
    zip_safe=False,
    python_requires=">=3.9",
    install_requires=[
        "astroid>=2.13.2",
        "autograd>=1.5",
        "black>=22.12.0",
        "certifi>=2022.12.7",
        "charset-normalizer>=3.0.1",
        "click>=8.1.3",
        "colorama>=0.4.6",
        "contourpy>=1.0.7",
        "cycler>=0.11.0",
        "dill>=0.3.6",
        "fonttools>=4.38.0",
        "idna>=3.4",
        "isort>=5.11.4",
        "kiwisolver>=1.4.4",
        "lazy-object-proxy>=1.9.0",
        "matplotlib>=3.6.3",
        "mypy-extensions>=0.4.3",
        "networkx>=3.0",
        "numpy>=1.24.1",
        "packaging>=23.0",
        "pandas>=1.5.3",
        "pathspec>=0.10.3",
        "Pillow>=9.4.0",
        "pip-upgrade>=0.0.6",
        "platformdirs>=2.6.2",
        "pointset>=0.1.5",
        "pyparsing>=3.0.9",
        "pyproj>=3.4.1",
        "PyQt6>=6.4.2",
        "PyQt6-Qt6>=6.4.2",
        "PyQt6-sip>=13.4.1",
        "python-dateutil>=2.8.2",
        "pytz>=2022.2.1",
        "PyYAML>=6.0",
        "requests>=2.28.2",
        "seaborn>=0.12.2",
        "scipy>=1.10.0",
        "six>=1.16.0",
        "tomli>=2.0.1",
        "tomlkit>=0.11.6",
        "typing_extensions>=4.4.0",
        "urllib3>=1.26.14",
        "wrapt>=1.14.1",
    ],
    entry_points={
        "console_scripts": [
            "trajectopy = trajectopy.__main__:main",
        ],
    },
)
