import maialib.maiacore as mc

def plotPartsActivity(score: mc.Score, **kwargs) -> None: ...
def plotPianoRoll(score: mc.Score, **kwargs) -> None: ...
def plotScorePitchEnvelope(score: mc.Score, **kwargs) -> None: ...
def plotChordsNumberOfNotes(score: mc.Score, **kwargs) -> None: ...
