from aioworkers.core.base import ExecutorEntity as ExecutorEntity, LoggingEntity as LoggingEntity
from aioworkers.net.sender import AbstractSender as AbstractSender

class SMTP(ExecutorEntity, LoggingEntity, AbstractSender):
    def set_config(self, config) -> None: ...
    def set_context(self, context) -> None: ...
    async def send_message(self, msg) -> None: ...
    async def make_message(self, msg): ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
