class ResponseStatus:
    
    # 401
    NOT_AUTHORIZED = 'NOT_AUTHORIZED'
    # 405
    NOT_ALLOWED = 'NOT_ALLOWED'
    # 404
    NOT_FOUND = 'NOT_FOUND'
    # 200
    OK = 'OK'
    RECEIVED = 'RECEIVED'
    OBJECT_CREATED = 'OBJECT_CREATED'
    OBJECT_EXISTS = 'OBJECT_EXISTS'
    OBJECT_UPDATED = 'OBJECT_UPDATED'
    OBJECT_DELETED = 'OBJECT_DELETED'
    # 400
    INVALID_FORMAT = 'INVALID_FORMAT'
    EXPECTED_VALUE = 'EXPECTED_VALUE'
    UNEXPECTED_VALUE = 'UNEXPECTED_VALUE'