# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lbsnstructure/temporal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from lbsnstructure import social_pb2 as lbsnstructure_dot_social__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1clbsnstructure/temporal.proto\x12\x0elbsn.structure\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1albsnstructure/social.proto\"\xc9\x05\n\x05\x45vent\x12*\n\x04pkey\x18\x01 \x01(\x0b\x32\x1c.lbsn.structure.CompositeKey\x12\x0c\n\x04name\x18\x02 \x01(\t\x12.\n\nevent_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10\x65vent_date_start\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0e\x65vent_date_end\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x08\x64uration\x18\x06 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x14\n\x0c\x65vent_latlng\x18\x07 \x01(\t\x12\x12\n\nevent_area\x18\x08 \x01(\t\x12\x30\n\nplace_pkey\x18\t \x01(\x0b\x32\x1c.lbsn.structure.CompositeKey\x12/\n\tcity_pkey\x18\n \x01(\x0b\x32\x1c.lbsn.structure.CompositeKey\x12\x32\n\x0c\x63ountry_pkey\x18\x0b \x01(\x0b\x32\x1c.lbsn.structure.CompositeKey\x12/\n\tuser_pkey\x18\x0c \x01(\x0b\x32\x1c.lbsn.structure.CompositeKey\x12\x19\n\x11\x65vent_description\x18\r \x01(\t\x12\x15\n\revent_website\x18\x0e \x01(\t\x12\x12\n\nevent_type\x18\x0f \x01(\t\x12\x19\n\x11\x65vent_share_count\x18\x10 \x01(\x03\x12\x18\n\x10\x65vent_like_count\x18\x11 \x01(\x03\x12\x1b\n\x13\x65vent_comment_count\x18\x12 \x01(\x03\x12\x19\n\x11\x65vent_views_count\x18\x13 \x01(\x03\x12\x1a\n\x12\x65vent_engage_count\x18\x14 \x01(\x03\x62\x06proto3')



_EVENT = DESCRIPTOR.message_types_by_name['Event']
Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'lbsnstructure.temporal_pb2'
  # @@protoc_insertion_point(class_scope:lbsn.structure.Event)
  })
_sym_db.RegisterMessage(Event)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENT._serialized_start=142
  _EVENT._serialized_end=855
# @@protoc_insertion_point(module_scope)
