from _typeshed import Incomplete

class CommandNotFound(RuntimeError): ...

def kwargs_from_argv(params, ns, argv): ...
def run(cmd, context, loop: Incomplete | None = ..., ns: Incomplete | None = ..., argv: Incomplete | None = ...): ...
