# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.countries_get_by_id_response_data import CountriesGetByIdResponseData
from sportmonks.type.countries_get_by_id_response_rate_limit import CountriesGetByIdResponseRateLimit
from sportmonks.type.countries_get_by_id_response_subscription import CountriesGetByIdResponseSubscription

class RequiredCountriesGetByIdResponse(TypedDict):
    pass

class OptionalCountriesGetByIdResponse(TypedDict, total=False):
    data: CountriesGetByIdResponseData

    subscription: CountriesGetByIdResponseSubscription

    rate_limit: CountriesGetByIdResponseRateLimit

    timezone: str

class CountriesGetByIdResponse(RequiredCountriesGetByIdResponse, OptionalCountriesGetByIdResponse):
    pass
