# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.odds_markets_all_response_subscription_item_add_ons import OddsMarketsAllResponseSubscriptionItemAddOns
from sportmonks.type.odds_markets_all_response_subscription_item_meta import OddsMarketsAllResponseSubscriptionItemMeta
from sportmonks.type.odds_markets_all_response_subscription_item_plans import OddsMarketsAllResponseSubscriptionItemPlans
from sportmonks.type.odds_markets_all_response_subscription_item_widgets import OddsMarketsAllResponseSubscriptionItemWidgets

class RequiredOddsMarketsAllResponseSubscriptionItem(TypedDict):
    pass

class OptionalOddsMarketsAllResponseSubscriptionItem(TypedDict, total=False):
    meta: OddsMarketsAllResponseSubscriptionItemMeta

    plans: OddsMarketsAllResponseSubscriptionItemPlans

    add_ons: OddsMarketsAllResponseSubscriptionItemAddOns

    widgets: OddsMarketsAllResponseSubscriptionItemWidgets

class OddsMarketsAllResponseSubscriptionItem(RequiredOddsMarketsAllResponseSubscriptionItem, OptionalOddsMarketsAllResponseSubscriptionItem):
    pass
