# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.odds_bookmakers_search_response_data import OddsBookmakersSearchResponseData
from sportmonks.type.odds_bookmakers_search_response_pagination import OddsBookmakersSearchResponsePagination
from sportmonks.type.odds_bookmakers_search_response_rate_limit import OddsBookmakersSearchResponseRateLimit
from sportmonks.type.odds_bookmakers_search_response_subscription import OddsBookmakersSearchResponseSubscription

class RequiredOddsBookmakersSearchResponse(TypedDict):
    pass

class OptionalOddsBookmakersSearchResponse(TypedDict, total=False):
    data: OddsBookmakersSearchResponseData

    pagination: OddsBookmakersSearchResponsePagination

    subscription: OddsBookmakersSearchResponseSubscription

    rate_limit: OddsBookmakersSearchResponseRateLimit

    timezone: str

class OddsBookmakersSearchResponse(RequiredOddsBookmakersSearchResponse, OptionalOddsBookmakersSearchResponse):
    pass
