# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.regions_get_by_id_response_subscription_item_add_ons import RegionsGetByIdResponseSubscriptionItemAddOns
from sportmonks.type.regions_get_by_id_response_subscription_item_meta import RegionsGetByIdResponseSubscriptionItemMeta
from sportmonks.type.regions_get_by_id_response_subscription_item_plans import RegionsGetByIdResponseSubscriptionItemPlans
from sportmonks.type.regions_get_by_id_response_subscription_item_widgets import RegionsGetByIdResponseSubscriptionItemWidgets

class RequiredRegionsGetByIdResponseSubscriptionItem(TypedDict):
    pass

class OptionalRegionsGetByIdResponseSubscriptionItem(TypedDict, total=False):
    meta: RegionsGetByIdResponseSubscriptionItemMeta

    plans: RegionsGetByIdResponseSubscriptionItemPlans

    add_ons: RegionsGetByIdResponseSubscriptionItemAddOns

    widgets: RegionsGetByIdResponseSubscriptionItemWidgets

class RegionsGetByIdResponseSubscriptionItem(RequiredRegionsGetByIdResponseSubscriptionItem, OptionalRegionsGetByIdResponseSubscriptionItem):
    pass
