# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_news_upcoming_pre_match_response_data import SportNewsUpcomingPreMatchResponseData
from sportmonks.type.sport_news_upcoming_pre_match_response_pagination import SportNewsUpcomingPreMatchResponsePagination
from sportmonks.type.sport_news_upcoming_pre_match_response_rate_limit import SportNewsUpcomingPreMatchResponseRateLimit
from sportmonks.type.sport_news_upcoming_pre_match_response_subscription import SportNewsUpcomingPreMatchResponseSubscription

class RequiredSportNewsUpcomingPreMatchResponse(TypedDict):
    pass

class OptionalSportNewsUpcomingPreMatchResponse(TypedDict, total=False):
    data: SportNewsUpcomingPreMatchResponseData

    pagination: SportNewsUpcomingPreMatchResponsePagination

    subscription: SportNewsUpcomingPreMatchResponseSubscription

    rate_limit: SportNewsUpcomingPreMatchResponseRateLimit

    timezone: str

class SportNewsUpcomingPreMatchResponse(RequiredSportNewsUpcomingPreMatchResponse, OptionalSportNewsUpcomingPreMatchResponse):
    pass
