# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_leagues_all_response_subscription_item_add_ons import SportLeaguesAllResponseSubscriptionItemAddOns
from sportmonks.type.sport_leagues_all_response_subscription_item_meta import SportLeaguesAllResponseSubscriptionItemMeta
from sportmonks.type.sport_leagues_all_response_subscription_item_plans import SportLeaguesAllResponseSubscriptionItemPlans
from sportmonks.type.sport_leagues_all_response_subscription_item_widgets import SportLeaguesAllResponseSubscriptionItemWidgets

class RequiredSportLeaguesAllResponseSubscriptionItem(TypedDict):
    pass

class OptionalSportLeaguesAllResponseSubscriptionItem(TypedDict, total=False):
    meta: SportLeaguesAllResponseSubscriptionItemMeta

    plans: SportLeaguesAllResponseSubscriptionItemPlans

    add_ons: SportLeaguesAllResponseSubscriptionItemAddOns

    widgets: SportLeaguesAllResponseSubscriptionItemWidgets

class SportLeaguesAllResponseSubscriptionItem(RequiredSportLeaguesAllResponseSubscriptionItem, OptionalSportLeaguesAllResponseSubscriptionItem):
    pass
