# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_referees_search_response_data_item import SportRefereesSearchResponseDataItem

SportRefereesSearchResponseData = typing.List[SportRefereesSearchResponseDataItem]
