# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_teams_search_response_subscription_item_add_ons import SportTeamsSearchResponseSubscriptionItemAddOns
from sportmonks.type.sport_teams_search_response_subscription_item_meta import SportTeamsSearchResponseSubscriptionItemMeta
from sportmonks.type.sport_teams_search_response_subscription_item_plans import SportTeamsSearchResponseSubscriptionItemPlans
from sportmonks.type.sport_teams_search_response_subscription_item_widgets import SportTeamsSearchResponseSubscriptionItemWidgets

class RequiredSportTeamsSearchResponseSubscriptionItem(TypedDict):
    pass

class OptionalSportTeamsSearchResponseSubscriptionItem(TypedDict, total=False):
    meta: SportTeamsSearchResponseSubscriptionItemMeta

    plans: SportTeamsSearchResponseSubscriptionItemPlans

    add_ons: SportTeamsSearchResponseSubscriptionItemAddOns

    widgets: SportTeamsSearchResponseSubscriptionItemWidgets

class SportTeamsSearchResponseSubscriptionItem(RequiredSportTeamsSearchResponseSubscriptionItem, OptionalSportTeamsSearchResponseSubscriptionItem):
    pass
