# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal


class RequiredSportTeamsByCountryIdResponseDataItem(TypedDict):
    pass

class OptionalSportTeamsByCountryIdResponseDataItem(TypedDict, total=False):
    id: typing.Union[int, float]

    sport_id: typing.Union[int, float]

    country_id: typing.Union[int, float]

    venue_id: typing.Union[int, float]

    gender: str

    name: str

    short_code: typing.Optional[str]

    image_path: str

    founded: typing.Union[int, float]

    type: str

    placeholder: bool

    last_played_at: typing.Optional[str]

class SportTeamsByCountryIdResponseDataItem(RequiredSportTeamsByCountryIdResponseDataItem, OptionalSportTeamsByCountryIdResponseDataItem):
    pass
