# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_coaches_latest_response_data import SportCoachesLatestResponseData
from sportmonks.type.sport_coaches_latest_response_rate_limit import SportCoachesLatestResponseRateLimit
from sportmonks.type.sport_coaches_latest_response_subscription import SportCoachesLatestResponseSubscription

class RequiredSportCoachesLatestResponse(TypedDict):
    pass

class OptionalSportCoachesLatestResponse(TypedDict, total=False):
    data: SportCoachesLatestResponseData

    message: str

    subscription: SportCoachesLatestResponseSubscription

    rate_limit: SportCoachesLatestResponseRateLimit

    timezone: str

class SportCoachesLatestResponse(RequiredSportCoachesLatestResponse, OptionalSportCoachesLatestResponse):
    pass
