# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_fixtures_by_ids_response_data import SportFixturesByIdsResponseData
from sportmonks.type.sport_fixtures_by_ids_response_rate_limit import SportFixturesByIdsResponseRateLimit
from sportmonks.type.sport_fixtures_by_ids_response_subscription import SportFixturesByIdsResponseSubscription

class RequiredSportFixturesByIdsResponse(TypedDict):
    pass

class OptionalSportFixturesByIdsResponse(TypedDict, total=False):
    data: SportFixturesByIdsResponseData

    subscription: SportFixturesByIdsResponseSubscription

    rate_limit: SportFixturesByIdsResponseRateLimit

    timezone: str

class SportFixturesByIdsResponse(RequiredSportFixturesByIdsResponse, OptionalSportFixturesByIdsResponse):
    pass
