# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from sportmonks.type.sport_league_by_id_response_subscription_item_add_ons import SportLeagueByIdResponseSubscriptionItemAddOns
from sportmonks.type.sport_league_by_id_response_subscription_item_meta import SportLeagueByIdResponseSubscriptionItemMeta
from sportmonks.type.sport_league_by_id_response_subscription_item_plans import SportLeagueByIdResponseSubscriptionItemPlans
from sportmonks.type.sport_league_by_id_response_subscription_item_widgets import SportLeagueByIdResponseSubscriptionItemWidgets

class RequiredSportLeagueByIdResponseSubscriptionItem(TypedDict):
    pass

class OptionalSportLeagueByIdResponseSubscriptionItem(TypedDict, total=False):
    meta: SportLeagueByIdResponseSubscriptionItemMeta

    plans: SportLeagueByIdResponseSubscriptionItemPlans

    add_ons: SportLeagueByIdResponseSubscriptionItemAddOns

    widgets: SportLeagueByIdResponseSubscriptionItemWidgets

class SportLeagueByIdResponseSubscriptionItem(RequiredSportLeagueByIdResponseSubscriptionItem, OptionalSportLeagueByIdResponseSubscriptionItem):
    pass
