from teradataml.analytics.meta_class import _AnalyticFunction
from teradataml.analytics.meta_class import _common_init

_uaf_functions = ['ACF',
                  'ArimaEstimate',
                  'ArimaValidate',
                  'DIFF',
                  'LinearRegr',
                  'MultivarRegr',
                  'PACF',
                  'PowerTransform',
                  'SeasonalNormalize',
                  'Smoothma',
                  'UNDIFF',
                  'Unnormalize',
                  'ArimaForecast',
                  'DTW',
                  'HoltWintersForecaster',
                  'MAMean',
                  'SimpleExp',
                  'BinaryMatrixOp',
                  'BinarySeriesOp',
                  'GenseriesFormula',
                  'MatrixMultiply',
                  'Resample',
                  'BreuschGodfrey',
                  'BreuschPaganGodfrey',
                  'CumulPeriodogram',
                  'DickeyFuller',
                  'DurbinWatson',
                  'FitMetrics',
                  'GoldfeldQuandt',
                  'Portman',
                  'SelectionCriteria',
                  'SignifPeriodicities',
                  'SignifResidmean',
                  'WhitesGeneral',
                  'Convolve',
                  'Convolve2',
                  'DFFT',
                  'DFFT2',
                  'DFFT2Conv',
                  'DFFTConv',
                  'GenseriesSinusoids',
                  'IDFFT',
                  'IDFFT2',
                  'LineSpec',
                  'PowerSpec',
                  'ExtractResults',
                  'InputValidator',
                  'MInfo',
                  'SInfo',
                  'TrackingOp']

for func in _uaf_functions:
    globals()[func] = type("{}".format(func), (_AnalyticFunction,),
                           {"__init__": lambda self, **kwargs: _common_init(self,
                            'uaf', **kwargs),
                            "__doc__": _AnalyticFunction.__doc__})
